### PR TITLE
ID arguments

### PR DESCRIPTION
**Pull request by fredericojordan**
- Allow `--bond-id` argument on `backup`/`livelog`/`reboot`/`reset`/`rfman`/`wifi` commands
- Allow multiple ID arguments on device/group deletion
- Use `kebab-case` on all arguments

### CODE REVIEW

**Review by chrismerck — COMMENTED** [review]
Is it possible to overload the parent class to inject this, rather than adding on each `Command`?

Note that when I was doodling this cli, I added  `select` because if user needs to specify the full bondid on every request, it felt like no real improvement over using cURL directly. But it is also cumbersome... I'm open to any level of changes to the `select` including removing it if it makes sense... just want as clean and usable an API as we can imagine.

**Comment by fredericojordan** [comment]
The main motivation in adding the `--bond-id` option is when running multiple commands at once (in parallel).
If we're grabbing the Bond ID from a local file, that restricts to running all the commands on the same Bond, making the`--bond-id` option required if we want to command multiple Bonds at once.
Since it doesn't seem like a very common case, I think we can stick to the `select` way of doing things and just leave the `--bond-id` option for when an override is needed.

**Review by marciogranzotto — DISMISSED** [review]
Awesome!

**Comment by fredericojordan** [comment]
> Is it possible to overload the parent class to inject this, rather than adding on each Command?

@chrismerck Yes, but it's not for every command that using a `--bond-id` option makes sense (eg. `bond discover`).

**Pull request merged**
